### ISSUE TITLE
Camera Panning doesn't work over information panes

### ISSUE THREAD

**Issue by MileoInc** [Diah50/Highborne-Battlecry#19]
Camera panning only works when the cursor is over the game map, not any of the info panels. Would be better to make camera panning happen when the cursor collides with the screen edge, and then lock the cursor to the game window. Also, to add camera controls to some keyboard buttons.

**Comment by bpodrygajlo** [comment]
@MileoInc can you check in the newest version?

**Comment by MileoInc** [comment]
Just checked, it's still doing it on my end. Although I did notice that the bottom right info panel is slightly pulled away from the screen edge on the right side, so you can use that little sliver of map to scroll with there. If you want a quick fix, you could just move all the panels slightly away from the edges of the screen.

**Comment by bpodrygajlo** [comment]
I'll rewrite the camera code instead of trying to fix it.

**Comment by bpodrygajlo** [comment]
Check #24

**Comment by bpodrygajlo** [comment]
Fixed
