### ISSUE TITLE
Invisible or non-spawning swordsmen

### ISSUE THREAD

**Issue by Diah50** [Diah50/Highborne-Battlecry#20]
I create some swordsmen and found out they weren't not spawning or they could be invisible.

**Comment by bpodrygajlo** [comment]
I cannot reproduce that. I remember this bug happening before but I think I fixed it. Can you try again and write down how you reproduced it?

**Comment by Diah50** [comment]
I clicked on the swordsman button from the town center building and that how I was able to reproduce the bug. the swordsman either disappeared or went invisible.

**Comment by bpodrygajlo** [comment]
Plase try again in a newer build

**Comment by bpodrygajlo** [comment]
fixed
